# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: glossary.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'glossary.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eglossary.proto\x12\x08glossary\"\x07\n\x05\x45mpty\"\x1e\n\x0eGetTermRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"2\n\x0e\x41\x64\x64TermRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\ndefinition\x18\x02 \x01(\t\"0\n\x0cTermResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\ndefinition\x18\x02 \x01(\t\":\n\x11TermsListResponse\x12%\n\x05terms\x18\x01 \x03(\x0b\x32\x16.glossary.TermResponse2\xc6\x01\n\x0fGlossaryService\x12;\n\x07GetTerm\x12\x18.glossary.GetTermRequest\x1a\x16.glossary.TermResponse\x12\x39\n\tListTerms\x12\x0f.glossary.Empty\x1a\x1b.glossary.TermsListResponse\x12;\n\x07\x41\x64\x64Term\x12\x18.glossary.AddTermRequest\x1a\x16.glossary.TermResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'glossary_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=28
  _globals['_EMPTY']._serialized_end=35
  _globals['_GETTERMREQUEST']._serialized_start=37
  _globals['_GETTERMREQUEST']._serialized_end=67
  _globals['_ADDTERMREQUEST']._serialized_start=69
  _globals['_ADDTERMREQUEST']._serialized_end=119
  _globals['_TERMRESPONSE']._serialized_start=121
  _globals['_TERMRESPONSE']._serialized_end=169
  _globals['_TERMSLISTRESPONSE']._serialized_start=171
  _globals['_TERMSLISTRESPONSE']._serialized_end=229
  _globals['_GLOSSARYSERVICE']._serialized_start=232
  _globals['_GLOSSARYSERVICE']._serialized_end=430
# @@protoc_insertion_point(module_scope)
