-- MySQL Script generated by MySQL Workbench
-- Tue Apr  8 22:35:56 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`ИГРА`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ИГРА` (
  `Название` VARCHAR(45) NOT NULL,
  `Производитель` VARCHAR(45) NOT NULL,
  `Мин_игроков` INT NOT NULL,
  `Макс_игроков` INT NOT NULL,
  `Мин_возраст` INT NULL,
  PRIMARY KEY (`Название`, `Производитель`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`КЛИЕНТ`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`КЛИЕНТ` (
  `Ид_клиента` VARCHAR(45) NOT NULL,
  `Фамилия` VARCHAR(100) NULL,
  `Имя` VARCHAR(100) NOT NULL,
  `Дата_рождения` DATE NULL,
  `Телефон` VARCHAR(45) NULL,
  `Почта` VARCHAR(45) NOT NULL,
  `Адрес` VARCHAR(45) NULL,
  PRIMARY KEY (`Ид_клиента`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ЗАКАЗ`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ЗАКАЗ` (
  `Номер` INT NOT NULL,
  `Получение` VARCHAR(45) NOT NULL,
  `Создан` DATETIME NOT NULL,
  PRIMARY KEY (`Номер`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`СОТРУДНИК`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`СОТРУДНИК` (
  `Таб_номер` VARCHAR(45) NOT NULL,
  `Фамилия` VARCHAR(100) NOT NULL,
  `Имя` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`Таб_номер`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ЗАКАЗАННАЯ_ИГРА`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ЗАКАЗАННАЯ_ИГРА` (
  `Номер_заказа` INT NOT NULL,
  `Название_игры` VARCHAR(45) NOT NULL,
  `Производитель` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Номер_заказа`, `Название_игры`, `Производитель`),
  INDEX `ИГРА_idx` (`Название_игры` ASC, `Производитель` ASC) VISIBLE,
  CONSTRAINT `ИГРА`
    FOREIGN KEY (`Название_игры` , `Производитель`)
    REFERENCES `mydb`.`ИГРА` (`Название` , `Производитель`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ЗАКАЗ`
    FOREIGN KEY (`Номер_заказа`)
    REFERENCES `mydb`.`ЗАКАЗ` (`Номер`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ЗАКРЕПЛЕННЫЙ_СОТРУДНИК`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ЗАКРЕПЛЕННЫЙ_СОТРУДНИК` (
  `Номер_сотрудника` VARCHAR(45) NOT NULL,
  `Номер_заказа` INT NOT NULL,
  PRIMARY KEY (`Номер_сотрудника`, `Номер_заказа`),
  INDEX `ЗАКАЗ_idx` (`Номер_заказа` ASC) VISIBLE,
  CONSTRAINT `СОТРУДНИК`
    FOREIGN KEY (`Номер_сотрудника`)
    REFERENCES `mydb`.`СОТРУДНИК` (`Таб_номер`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ЗАКАЗ`
    FOREIGN KEY (`Номер_заказа`)
    REFERENCES `mydb`.`ЗАКАЗ` (`Номер`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ПОЛУЧАТЕЛЬ`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ПОЛУЧАТЕЛЬ` (
  `Номер_заказа` INT NOT NULL,
  `Ид_клиента` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Номер_заказа`),
  INDEX `КЛИЕНТ_idx` (`Ид_клиента` ASC) VISIBLE,
  CONSTRAINT `ЗАКАЗ`
    FOREIGN KEY (`Номер_заказа`)
    REFERENCES `mydb`.`ЗАКАЗ` (`Номер`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `КЛИЕНТ`
    FOREIGN KEY (`Ид_клиента`)
    REFERENCES `mydb`.`КЛИЕНТ` (`Ид_клиента`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
